name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        # https://github.com/actions/checkout
        uses: actions/checkout@v6

      - name: Run Cypress tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v7
        with:
          # check if the types agree
          build: npm run types

      # https://github.com/actions/upload-artifact
      - uses: actions/upload-artifact@v7
        name: Store any error screenshots 🖼
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v7
        name: Store any videos 🖼
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  release:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v6

      - name: Install only the semantic release 📦
        run: npm install semantic-release

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
